name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: When I try to... I expect... but instead...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code to reproduce the issue
      placeholder: |
        ```python
        from conduit import Router, Query
        router = Router()
        # ...
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      value: |
        - Conduit version: [e.g., 0.1.0]
        - Python version: [e.g., 3.13]
        - OS: [e.g., Ubuntu 22.04]
        - LLM Provider: [e.g., OpenAI, Anthropic]
        - Redis/PostgreSQL: [yes/no]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (if any)
      render: shell

  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I've searched existing issues for duplicates
          required: true
        - label: I'm using the latest version
          required: false
